source "http://gems.github.com"
source "http://rubygems.org"

gemspec path: File.expand_path(File.dirname(__FILE__) + "/../")

gem 'voluntary', '0.1.0.rc4', path: '../local_gems/voluntary'

gem "rack-cors", "~> 0.2.4", :require => "rack/cors"
gem "thin", "~> 1.3.1", :require => false
gem "settingslogic", :git => "https://github.com/binarylogic/settingslogic.git"
gem "acts_as_markup", :git => "git://github.com/vigetlabs/acts_as_markup.git"
gem "auto_html", :git => "git://github.com/Applicat/auto_html"
gem "recaptcha", :require => "recaptcha/rails"
gem "sinatra", :require => false
gem "addressable", "~> 2.2", :require => "addressable/uri"
gem "jasmine", :git => "https://github.com/pivotal/jasmine-gem.git"
gem "zip"

# view
gem "will_paginate", :github => "mislav/will_paginate"

group :development do
  gem "linecache", "0.46", :platforms => :mri_18
  gem "capistrano", :require => false
  gem "capistrano_colors", :require => false
  gem "capistrano-ext", :require => false
  gem "yard", :require => false
  
  gem 'better_errors'
  gem 'binding_of_caller'
  # currently raises segmentation fault
  #gem 'meta_request'
  gem 'brakeman'
  gem 'rails_best_practices'
  gem 'sextant'
end

group :test do
  gem 'capybara', '~> 1.1.2', :require => false
  #gem 'capybara-webkit'
  gem 'cucumber-rails', '1.3.0'
  gem 'cucumber-rails-training-wheels'
  gem 'timecop'
  gem 'factory_girl_rails', '1.7.0'
  gem 'fixture_builder', '0.3.3'
  gem 'fuubar', '>= 1.0'
  gem 'selenium-webdriver', '~> 2.22.1'
  gem 'spork', '~> 1.0rc2'
  gem 'guard-rspec'
  gem 'guard-spork'
  gem 'guard-cucumber'
  gem 'launchy'
  
  gem "rspec-instafail", ">= 0.1.7", :require => false
  gem "webmock", "~> 1.7", :require => false
  gem "simplecov", :require => false
end

group :development, :test do
  gem "debugger", :platforms => :mri_19
  gem "ruby-debug", :platforms => :mri_18
end

group :assets do
  gem "therubyracer", :platforms => :ruby
  gem "asset_sync", :require => nil
end

group :production do
  gem "fastercsv", "1.5.5", :require => false
  gem "rack-ssl", :require => "rack/ssl"
  gem "rack-rewrite", "~> 1.2.1", :require => false
  gem "rack-google-analytics", :require => "rack/google-analytics"
  gem "rack-piwik", :require => false
end